exp_name: main
task_names: 
prompt_idxs: 
models: [
    mistral-large-2407
] # None or List[str]
resume_model: 0 # Resume idx when models is None
system: 
max_tokens: 8192
seed: 12 # uniquness of problems is not guaranteed for different seeds
num_workers: 20