# generation
exp_name: serial_subtask
num_serial_subtasks: [1, 5, 10, 20]
num_samples: [100, 10, 10, 10]

task_names:
prompt_idxs: #[0, 5, 10, 15, 20, 25, 30, 35, 40, 45]

models: [
  # claude-3-sonnet-20240229,
  claude-3-5-sonnet-20240620,
  # gemini-1.5-pro-latest,
  # gemini-1.0-pro-latest,
  # o1-mini-2024-09-12,
  gpt-4o-2024-05-13,
  # gpt-4-turbo-2024-04-09,
  # gpt-3.5-turbo-0125,
] # None or List[str]
resume_model: 0 # Resume idx when models is None
system: 
max_tokens: 2048
seed: 42
num_workers: 100

evaluators: [serial_subtask_evaluator]
